partial update ; removing redundant code introduced bugs, this commit captures the fix for those that have arisen so far.

diff --git a/goose b/goose
--- a/goose
+++ b/goose
@@ -25,30 +25,17 @@ elif [[ "${APP_PATH}" != "${PROJECT_PATH}" && -f "${PROJECT_PATH}/${APP_NAME}" ]
     exit $?
 fi
 
-if [[ ! -d "${APP_PATH}/.goose" || ! -f "${APP_PATH}/.goose/arg_parse.bash" ]]; then
-    echo "${PROJECT_PATH}/.goose/arg_parse.bash is missing! Critical dependency! Exiting..." >&2
+if [[ ! -d "${APP_PATH}/.goose" || ! -f "${APP_PATH}/.goose/core.bash" ]]; then
+    echo "${PROJECT_PATH}/.goose/core.bash is missing! Critical dependency! Exiting..." >&2
     exit 255
 fi
-source ${APP_PATH}/.goose/arg_parse.bash
+source ${APP_PATH}/.goose/core.bash
 
-# if [[ ! -f "${APP_PATH}/.goose/dag.bash" ]]; then
-#     error "${APP_PATH}/.goose/dag.bash is missing! Critical dependency! Exiting..." 255
-# fi
-# source .goose/dag.bash
-
-# if [[ ! -f "${APP_PATH}/.goose/test.bash" ]]; then
-#     error "${APP_PATH}.goose/test.bash is missing! Critical dependency! Exiting..." 255
-# fi
-# source $(.goose/test.bash
-
-if [[ ! -d "${PROJECT_PATH}/targets/" ]]; then
-    error "no target directory! Nothing to run! Exiting..." 255
+if [[ ! -f "${APP_PATH}/.goose/namespace.bash" ]]; then
+    echo "${PROJECT_PATH}/.goose/namespace.bash is missing! Critical dependency! Exiting..." >&2
+    exit 255
 fi
-
-if [[ ! -f "${PROJECT_PATH}/targets/common.bash" ]]; then
-    error "Missing common target! Critical dependency! Exiting..." 255
-fi
-source ${PROJECT_PATH}/targets/common.bash
+source ${APP_PATH}/.goose/namespace.bash
 
 function init () {
     [[ -f ${PROJECT_PATH}/.env ]] && source ${PROJECT_PATH}/.env
@@ -63,14 +50,10 @@ function cleanup () {
 function main () {
     init
 
-    validate_flags
-    execute_flags
-
-    [[ ${IGNORE_DEPENDENCIES} -eq 0 ]] && validate_dependencies
-    validate_target
+    find_root_namespace
+    run_namespace
 
     cleanup
 }
-
 
 main
